### ISSUE TITLE
No method `setReorderingAllowed` found

### ISSUE THREAD

**Issue by JonnyBurger** [kmagiera/react-native-screens#43]
I'm using react-native 0.56 and have problems with Android.

I think I linked the library correctly and it compiles:

<details>

<img src="https://user-images.githubusercontent.com/1629785/48845703-7eee6080-ed9d-11e8-91f6-fbc4dc50c8e0.png"></img>
</details>
<details>

<img src="https://user-images.githubusercontent.com/1629785/48845788-b9f09400-ed9d-11e8-9ff1-7b320ef5cdf8.png"></img>
</details>

But then I get this runtime error when starting the app:

```
    java.lang.NoSuchMethodError: No virtual method setReorderingAllowed(Z)Landroid/support/v4/app/FragmentTransaction; in class Landroid/support/v4/app/FragmentTransaction; or its super classes (declaration of 'android.support.v4.app.FragmentTransaction' appears in /data/app/bestande.bestande-1/base.apk)
        at com.swmansion.rnscreens.ScreenContainer.getOrCreateTransaction(ScreenContainer.java:92)
        at com.swmansion.rnscreens.ScreenContainer.attachScreen(ScreenContainer.java:105)
        at com.swmansion.rnscreens.ScreenContainer.updateIfNeeded(ScreenContainer.java:168)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.java:129)
        at android.view.View.dispatchAttachedToWindow(View.java:15509)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4456)
        at android.view.ViewGroup.addView(ViewGroup.java:4258)
        at android.view.ViewGroup.addView(ViewGroup.java:4198)
        at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:45)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:437)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:227)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:894)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1001)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1061)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by kmagiera** [comment]
Hey @JonnyBurger! Thanks for reaching out.

I believe the issue you're experiencing is due to an old version of support library your app compiles with. Could you please check what version are you using so that we can see if that in fact is the problem? If you use one of the recent RN app templates the version should be located in `android/build.gradle` where in `ext` section you should have `supportLibVersion` defined. In case of an older app template the location may differ. LMK if you could find it

**Comment by JonnyBurger** [comment]
I have in the meanwhile updated to React Native 0.57 and have also changed some SDK versioning stuff.

Just tried it again now and it works! Nice.

Thanks for the help! If a lot of people have the same problem, I can try to pinpoint what was the exact issue.
